### ISSUE TITLE
Add php mvc skeleton

### ISSUE THREAD

**Issue by ahegazy** [mfouad/awesome-egypt-opensource#5]
Hi all, 
So i have this project from couple of years, it's a template to build your application on, so i don't to if it's eligible to be added to the list
please check the [repo](https://github.com/ahegazy/php-mvc-skeleton) and add it to the list :D 

## Description
A PHP OOP web application skeleton that uses MVC architectural pattern to create a basic application that contains login and multi language systems and can be used in any web project.

Thanks

**Comment by mfouad** [comment]
@ahegazy How is this a template? this is almost a full blown framework man :open_mouth: !!
I think it should qualify, not sure if it will compare to Laravel or Symphony .. and probably that is why it is old. 

If you are still interested in contributions from the community then lets add it, if you think it is dead, then maybe there is no reason to add it.
please open a pull request and add it to the list if so.
